const fs = require('node:fs');
const path = require('node:path');

function readLegacyTemplate() {
  const templatePath = path.resolve(__dirname, '../../command/cowork.legacy.md');
  return fs.readFileSync(templatePath, 'utf8');
}

function buildCoworkCommand(options = {}) {
  const mode = options.mode || 'balanced';
  const template = readLegacyTemplate();
  const banner = `<!-- generated by cowork runtime adapter, mode=${mode} -->\n`;
  return `${banner}${template}`;
}

function writeBuiltCommand(outputPath, options = {}) {
  const content = buildCoworkCommand(options);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');
}

module.exports = {
  buildCoworkCommand,
  writeBuiltCommand
};
